name: CI
on:
  push:
    branches:
      - main

jobs:
  ci-and-publish:
    uses: quentinadam/deno-ci-workflow/.github/workflows/ci-publish.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
