name: ci
on:
  push:
    branches:
      - main
jobs:
  check-deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check
      - run: deno lint
      - run: deno task check
  check-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          node --input-type=module -e "
          import fs from 'node:fs';
          const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf-8'));
          const packageLockJson = JSON.parse(fs.readFileSync('package-lock.json', 'utf-8'));
          if (packageJson.version !== packageLockJson.version) {
              console.error(\`Version mismatch: package.json (\${packageJson.version}) and package-lock.json (\${packageLockJson.version})\`);
              process.exit(1);
          } else {
              console.log('Version numbers match.');
          }
          "
      - run: npm ci
      - run: npm run build
